# Generated by Django 3.2.7 on 2021-11-24 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.IntegerField(primary_key=True, serialize=False)),
                ('al_nome', models.CharField(max_length=120, unique=True)),
                ('al_chamada', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Aula',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_nome', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id_escola', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Escola',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('t_ano', models.IntegerField(blank=True, null=True)),
                ('t_turma', models.CharField(blank=True, max_length=20, null=True)),
                ('t_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escola')),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nome', models.CharField(max_length=120, unique=True)),
                ('p_disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('p_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('p_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_presenca', models.BooleanField(default=False)),
                ('data_aula', models.DateTimeField(auto_now=True)),
                ('qte_aulas', models.IntegerField(blank=True, default=25, null=True)),
                ('id_aluno', models.ManyToManyField(to='core.Aluno')),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aula')),
            ],
            options={
                'db_table': 'Presenca',
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='d_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='aula',
            name='au_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina'),
        ),
        migrations.AddField(
            model_name='aula',
            name='au_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='al_disciplina',
            field=models.ManyToManyField(blank=True, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='al_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='al_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='al_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
